import './globals.css'
import { Inter } from 'next/font/google'
import Navigation from '@/components/Navigation'
import Footer from '@/components/Footer'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Navigation />

        <div className="bg-gray-100" data-theme="light">

          <div className="mx-auto max-w-screen-md px-4 py-8">
            {children}
          </div>

        </div>

        <Footer />
      </body>
    </html>
  )
}
